#!/usr/bin/perl
#

my @output = `ps -ef | grep -i 'ssh -N'`;
foreach $line ( @output ) {
    #print $line;
    if ($line =~ /8384/ && $line =~ /\s*\d+\s*(\d+)/i) {
        my $cmd = "kill -9 $1";
        print $cmd."\n";
        `$cmd`;
    }
}

